import os
import json
from datetime import datetime
from typing import Any, Dict, List, Optional

class TraceLogger:
    """
    A service class responsible for logging agent execution traces and decisions.
    
    This logger creates structured trace entries to record the step-by-step reasoning
    and outputs of various agents within the Fire Crisis Response System, supporting
    traceability and hackathon demo runs.
    """

    def __init__(self, default_timestamp: Optional[str] = None) -> None:
        """
        Initializes the TraceLogger with an optional default session timestamp.
        
        Args:
            default_timestamp (str, optional): The default timestamp to use for logging traces.
                                               If not provided, current system time is used.
        """
        if default_timestamp:
            self.default_timestamp = default_timestamp
        else:
            self.default_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    def write_trace(
        self,
        agent_name: str,
        step_type: str,
        reasoning: str,
        confidence_before: float,
        confidence_after: float,
        inputs: Optional[Dict[str, Any]] = None,
        output: Optional[Dict[str, Any]] = None,
        tool_calls: Optional[List[Dict[str, Any]]] = None,
        duration_ms: int = 0,
        timestamp: Optional[str] = None,
    ) -> None:
        """
        Appends an agent decision trace entry to the traces JSON file.
        
        Args:
            agent_name (str): The name of the agent making the decision.
            step_type (str): The type of action or step being logged.
            reasoning (str): The logical reasoning explaining the agent's action.
            inputs (dict): Input parameters passed to the agent or step.
            output (dict): The output generated by the agent or step.
            confidence_before (float): The agent's confidence score before this step.
            confidence_after (float): The agent's confidence score after this step.
            tool_calls (list): The tools invoked during this step, if any.
            duration_ms (int): Time elapsed during the step execution, in milliseconds.
            timestamp (str, optional): Overriding timestamp. If not specified, the session
                                       or current system timestamp is used.
        """
        # Determine the timestamp to use for the trace file and structure
        actual_timestamp = timestamp if timestamp else self.default_timestamp
        
        # Structure the trace dictionary
        trace_entry = {
            "agent_name": agent_name,
            "step_type": step_type,
            "reasoning": reasoning,
            "inputs": inputs or {},
            "output": output or {},
            "confidence_before": confidence_before,
            "confidence_after": confidence_after,
            "tool_calls": tool_calls or [],
            "duration_ms": duration_ms,
            "timestamp": actual_timestamp,
        }

        # Sanitize timestamp for filename usage (replace ':' with '-' to support Windows OS)
        safe_timestamp = actual_timestamp.replace(":", "-")
        filename = f"traces_{safe_timestamp}.json"
        
        # Ensure log directory exists at the workspace root
        current_dir = os.path.dirname(os.path.abspath(__file__))
        workspace_root = os.path.abspath(os.path.join(current_dir, "..", ".."))
        log_dir = os.path.join(workspace_root, "logs", "demo_runs")
        os.makedirs(log_dir, exist_ok=True)
        file_path = os.path.join(log_dir, filename)

        # Write or append trace data
        traces: List[Dict[str, Any]] = []
        if os.path.exists(file_path):
            try:
                with open(file_path, "r", encoding="utf-8") as f:
                    content = f.read().strip()
                    if content:
                        loaded_data = json.loads(content)
                        if isinstance(loaded_data, list):
                            traces = loaded_data
                        else:
                            traces = [loaded_data]
            except Exception:
                # If file exists but is corrupted, fallback to empty list
                traces = []

        traces.append(trace_entry)

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(traces, f, indent=2, ensure_ascii=False)
