name: ciro_fire_orchestrator
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  image: ^4.0.0
  connectivity_plus: ^5.0.0
  cupertino_icons: ^1.0.8

  # CIRO Hackathon Core Dependencies
  http: ^1.6.0
  image_picker: ^1.0.4

  google_fonts: ^5.1.0
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0
  web_socket_channel: ^3.0.0
  web: ^1.0.0
  fl_chart: ^1.2.0
  intl: ^0.20.2
  sqflite: ^2.4.2+1
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  video_player: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen: ^5.14.1
  build_runner: ^2.4.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/models/